apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: orders-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push-master
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref == 'refs/heads/master'"
      bindings:
        - ref: orders-trigger-binding
      template:
        ref: orders-trigger-template
