apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: orders-cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: master
    - name: image-name
      type: string
    - name: base-url
      type: string

  workspaces:
    - name: shared-workspace

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
    - name: lint
      taskRef:
        name: lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: test
      taskRef:
        name: test
        kind: Task
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
    - name: bdd-tests
      taskRef:
        name: bdd-tests
      runAfter:
        - deploy
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: BASE_URL
          value: $(params.base-url)
