apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: orders-trigger-template
spec:
  params:
    - name: repo-url
    - name: revision
      default: master
    - name: image-name
    - name: base-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: orders-cd-
      spec:
        pipelineRef:
          name: orders-cd-pipeline
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)
          - name: image-name
            value: $(tt.params.image-name)
          - name: base-url
            value: $(tt.params.base-url)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: pipeline-pvc
